AllCops:
  NewCops: enable
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.6.4
  # 除外するファイル
  Exclude:
    - vendor/bundle/**/*
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'node_modules/*'

# 規約違反をファイルに記載する。
inherit_from: .rubocop_todo.yml